### PR TITLE
link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello!

The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that in what I understand to to be either static links, or code that generates new DOI links. Code to detect or test the old URLs should not be affected.

Cheers :-)

### CODE REVIEW

**Comment by MisanthropicBit** [comment]
Thanks for the PR. I was not aware of the updated resolver, but `https` is certainly a better default.

I'll probably have time to look at the link in detail tonight and merge it in.

**Comment by katrinleinweber** [comment]
I looked through a [Travi log and it seems my commit did break the 2 DOI tests](https://travis-ci.org/MisanthropicBit/bibpy/jobs/342808831#L584). I'm not sure why, though, sorry. On my macOS 10.13.3 with python3.6, the error is different than on Travis:

```{python}
______________________ test_doi __________________________________________________________________________

    @not_on_travis
    def test_doi():
        with vcr.use_cassette('fixtures/vcr_cassettes/doi.yaml'):
            doi = '10.1145/1015530.1015557'
>           entry = bibpy.doi.retrieve(doi)

tests/test_doi.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bibpy/doi/__init__.py:28: in retrieve
    handle = urlopen(req)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:223: in urlopen
    return opener.open(url, data, timeout)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:526: in open
    response = self._open(req, data)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:544: in _open
    '_open', req)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:504: in _call_chain
    result = func(*args)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:1361: in https_open
    context=self._context, check_hostname=self._check_hostname)
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py:1321: in do_open
    r = h.getresponse()
```

**Comment by MisanthropicBit** [comment]
> I looked through a Travi log and it seems my commit did break the 2 DOI tests. I'm not sure why, though, sorry.

The build (and `test_doi.py`) was broken before you submitted your PR, namely this error message:

```__________________________ ERROR at setup of test_doi __________________________
Error evaluating 'skipif' expression
    true
NameError: name 'true' is not defined
________________________ ERROR at setup of test_doi_raw ________________________
Error evaluating 'skipif' expression
    true
NameError: name 'true' is not defined
```

I'm not sure why this happens since I've used pytest's `skipif` before without issues, but I'm looking into it now. Actually, the pytest marker should ensure that the tests do not even run on Travis.

> On my macOS 10.13.3 with python3.6, the error is different than on Travis:

Strange, on my macOS Sierra 10.12.6 running `tox -e py36` works without issue. Are you missing part of the stack trace with the raised exception (the travis link links to my log)? I've tested your changes locally though, and things seem to work.

**Comment by katrinleinweber** [comment]
OK, thanks for confirming! I don't have my own Travis set-up, so yes, the link goes to yours ;-)

**Comment by MisanthropicBit** [comment]
I've fixed the issue with `skipif` so just need to fix the remaining issues on Travis, and I'll merge your stuff, in unless you want to make any changes to your PR so it runs with Python 3.6 on your machine.

**Comment by katrinleinweber** [comment]
Sorry, but I'm not a user of bibpy, so I don't need to get it running on my machine. Just noticed the old DOI link and wanted to update it.

**Comment by MisanthropicBit** [comment]
> Sorry, but I'm not a user of bibpy, so I don't need to get it running on my machine. Just noticed the old DOI link and wanted to update it.

That's ok. Thanks again for the PR :) Do you mind capitalizing your commit message, i.e.: "Link DOIs to preferred resolver" (sorry for the missing `contributing.md` guidelines)? Then I'll merge 👍

**Comment by katrinleinweber** [comment]
I don't really understand the reason (beyond "it's in a style guide") for capitalising, but here you are :-)

**Comment by MisanthropicBit** [comment]
> I don't really understand the reason (beyond "it's in a style guide") for capitalising, but here you are :-)

It's just an arbitrary choice, but imo it's always a good idea to stick to one style for consistency, especially with PRs from multiple people with different styles etc. Thanks!

**Pull request merged**
